<?xml version="1.0"?>
<robot name="ydrobot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- PROPERTY LIST -->
    <xacro:property name="M_PI" value="3.1415926"/>
    <!-- <xacro:property name="base_radius" value="0.20"/> -->
    <xacro:property name="base_length" value="0.16"/>
        <!-- 轮子直径 -->
    <xacro:property name="wheel_radius" value="0.0775"/>
        <!-- 轮子宽度 -->
    <xacro:property name="wheel_length" value="0.04"/>

    <xacro:property name="wheel_joint_y" value="0.19"/>
    <!-- <xacro:property name="wheel_joint_z" value="0.05"/> -->

    <xacro:property name="caster_radius" value="${wheel_radius/2}"/> <!-- wheel_radius - ( base_length/2 - wheel_joint_z) -->
    <xacro:property name="caster_joint_x" value="0.18"/>

    <!-- Defining the colors used in this robot -->
    <material name="yellow">     
        <color rgba="1 0.4 0 1"/>
    </material>
    <material name="black">
        <color rgba="0 0 0 0.95"/>
    </material>
    <material name="gray">
        <color rgba="0.75 0.75 0.75 1"/>
    </material>
    
    <!-- Macro for robot wheel     -->
    <xacro:macro name="wheel" params="prefix reflect">
        <joint name="${prefix}_wheel_joint" type="continuous">
            <origin xyz="0 ${reflect*wheel_joint_y} ${wheel_radius}" rpy="${M_PI/2} 0 0"/>
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="${prefix}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length = "${wheel_length}"/>
                </geometry>
                <material name="gray" />
            </visual>
        </link>
    </xacro:macro>

    <!-- Macro for robot caster -->
    <xacro:macro name="caster" params="prefix reflect">
        <joint name="${prefix}_caster_joint" type="continuous">
            <origin xyz="${reflect*caster_joint_x} 0 ${caster_radius}" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="${prefix}_caster_link"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="${prefix}_caster_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <sphere radius="${caster_radius}" />
                </geometry>
                <material name="black" />
            </visual>
        </link>
    </xacro:macro>

    <xacro:macro name="ydrobot_agv_base">
        <link name="base_link">
            <visual>
                <origin xyz=" 0 0 ${wheel_radius+0.05}" rpy="0 0 0" />
                <geometry>
                    <!-- 长 宽 高 -->
		             <box size="0.65 0.4 0.10"/>
		        </geometry>
                <material name="yellow" />
            </visual>
        </link>

        <xacro:wheel prefix="right" reflect="-1"/>
        <xacro:wheel prefix="left" reflect="1"/>
        <xacro:caster prefix="back" reflect="-1"/>
        <xacro:caster prefix="front" reflect="1"/>
    </xacro:macro>
</robot>
