<?xml version="1.0"?>
<robot name="ydrobot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <!-- PROPERTY LIST -->
    <xacro:property name="M_PI" value="3.1415926"/>
    <!-- <xacro:property name="base_radius" value="0.20"/> -->
    <!-- 底盘高度 -->
    <xacro:property name="base_length" value="0.37"/>
    <xacro:property name="wheel_radius" value="0.085"/>
    <xacro:property name="wheel_length" value="0.067"/>
    <xacro:property name="wheel_joint_y" value="0.19"/>
    <!-- <xacro:property name="wheel_joint_z" value="0.05"/> -->
    <xacro:property name="caster_length" value="0.015"/>
    <xacro:property name="caster_radius" value="${wheel_radius/2}"/>
    <xacro:property name="caster_joint_x" value="0.18"/>

    <!-- Defining the colors used in this robot -->
    <material name="yellow">
        <color rgba="1 0.4 0 1"/>
    </material>
    <material name="black">
        <color rgba="0 0 0 0.75"/>
    </material>
    <material name="gray">
        <color rgba="0.75 0.75 0.75 1"/>
    </material>
    <material name="white">
        <color rgba="1  1 1 0.85"/>
    </material>

    <!-- Macro for robot wheel -->
    <xacro:macro name="wheel" params="prefix reflect">
        <joint name="${prefix}_wheel_joint" type="continuous">
            <origin xyz="0 ${reflect*wheel_joint_y} 0" rpy="${M_PI/2} 0 0"/>
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="${prefix}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
            </collision>
        </link>
    </xacro:macro>

    <!-- Macro for robot caster -->
    <xacro:macro name="caster" params="prefix reflectl reflectr">
        <joint name="${prefix}_caster_joint" type="continuous">
            <origin xyz="${reflectl*4*caster_radius} ${reflectr*2*caster_radius} -${caster_radius}" rpy="${M_PI/2} 0 0"/>
            <parent link="base_link"/>
            <child link="${prefix}"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="${prefix}">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${caster_radius}" length="${caster_length}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${caster_radius}" length="${caster_length}"/>
                </geometry>
            </collision>
        </link>
    </xacro:macro>
    <xacro:include filename="$(find rm_description)/urdf/RM65/rm_65_add.urdf.xacro"/>
    <xacro:macro name="ydrobot_agv_circle">
        <link name="base_link">
            <visual>
                <origin xyz="0 0 ${base_length/2}" rpy="0 0 0"/>
                <geometry>
                    <!-- <cylinder radius="0.23" length="${base_length}"/> -->
                    <box size="0.7 0.47 0.37"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0 0 ${base_length/2}" rpy="0 0 0"/>
                <geometry>
                    <!-- <cylinder radius="0.23" length="${base_length}"/> -->
                    <box size="0.70 0.47 0.37"/>
                </geometry>
            </collision> 
        </link>

        <xacro:wheel prefix="right" reflect="-1"/>
        <xacro:wheel prefix="left" reflect="1"/>
        <xacro:caster prefix="front_r" reflectl="-1" reflectr="1"/>
        <xacro:caster prefix="front_l" reflectl="1" reflectr="-1"/>
        <xacro:caster prefix="back_r" reflectl="-1" reflectr="-1"/>
        <xacro:caster prefix="back_l" reflectl="1" reflectr="1"/>

        <xacro:rm_65 parent="base_link">
            <origin xyz="0.145 0.0 ${base_length}" rpy="0.0 0.0 0.0"/>
        </xacro:rm_65>
    </xacro:macro>
</robot>
